### ISSUE TITLE
Mission "Catalytic Ramscoops 1D"

### ISSUE THREAD

**Issue by Durzai** [kestrel1110/Navy-Campaign#21]
Mission "Catalytic Ramscoops 1D" (Efficiency Test) randomly triggered part-way through the first act of the Navy Campaign. It is also missing it's description as shown in the screenshot.

![Ramscoop1](https://github.com/kestrel1110/Navy-Campaign/assets/105894839/ee5316d8-81c9-40f8-890f-c9981a307768)

**Comment by kestrel1110** [comment]
Should be fixed now
