### ISSUE TITLE
Multiple significant typos

### ISSUE THREAD

**Issue by Xhaldor** [kestrel1110/Navy-Campaign#35]
Heya, am Xhaldor and i've been playing this mod for a couple of days now. I've been fixing a few bugs here and there and I am here to say that it is full of minor mistakes which lead to the missions not starting. I've already posted some minor forks and fixes, including fixing Geminus storyline and now fixing Valhalla storyline. I am posting this issue to suggest double-checking the code making sure it's all correct. I am also asking to see if there is any way to communicate directly with the group- as I am quite interested in this mod.

**Comment by Xhaldor** [comment]
FYI, I am new to Github.

**Comment by Xhaldor** [comment]
Found a new error stopping the storyline, during Electrons 1F after you complete you get to choose your response but both give you blank and the story doesn't update to the event. I have these errors so far but I haven't found the fix.

Warning: Closing quotation mark is missing:
file "C:/Users/xhald/AppData/Roaming/endless-sky/plugins/Navy-Campaign-master/data/navy 1 start.txt"
L1304:   mission "Electrons 1F"
L1310:     on offer
L1311:       conversation
L1312:         `After taking care of some business, you head back to the main planetary spaceport and to the spaceport lounge as you remember John saying, and sure enough, you see him there waiting. You go over to him, and he tells you what your task is. "Lt. Commander, your job is to get to the <waypoint> system. There you will find a Mule and a Barb in orbit, and you are to disable them without destroying them. My engineers are installing analysis cameras on your hull as we speak. They will film the interaction for my analysts to deal with, and I will need your ships logs as well. Once you're done, report back to me and give me an honest assessment of the engagement so I may finalize our adjustments. Any questions?"`

Warning: Closing quotation mark is missing:
file "C:/Users/xhald/AppData/Roaming/endless-sky/plugins/Navy-Campaign-master/data/navy 1 start.txt"
L1304:   mission "Electrons 1F"
L1324:     on complete
L1327:       conversation
L1328:         `You arrive on Valhalla and proceed to the secure facility where John works, and he meets you outside of your ship. "Well, how was the fight, <first>?"`

Warning: Closing quotation mark is missing:
file "C:/Users/xhald/AppData/Roaming/endless-sky/plugins/Navy-Campaign-master/data/navy 1 start.txt"
L1304:   mission "Electrons 1F"
L1324:     on complete
L1327:       conversation
L1338:         `"Yes they were, and I'm glad you weren't harmed- I'll be reviewing the resources from your ship and we should have these ready in the coming days."`

**Comment by Xhaldor** [comment]
I will be busy this following week so I wont' get to test out the mod as much. However you are doing great.

**Comment by Xhaldor** [comment]
It seems like you can skip Electrons 1F which lets you start Electrons 2A (The one where you disable an electron vessel) but it doesn't give out any info, blank text, blank mission, no events. Once you defeat it and return- no logs, you finish the mission and 2-4 days later another one asks to return to do Electrons 2B, but there is no waypoint and when you land nothing happens. It seems the entire text is completely wrong as it's missing many closing marks.

**Comment by kestrel1110** [comment]
Yeah so there is a discord-- gonna post it in the readme most likely
Been working on and off, I'm trying to get through writing it all and am up to the navy invasion of the FW but I have not been able to bugtest past Gemini's 2b
It has been about 3 years since I last worked on anything endless-sky related and my code is a bit rusty and have been struggling to fix things
Any help is welcome and thanks for the interest and contribution!

**Comment by Xhaldor** [comment]
No problem! Am juts here because I want to contribute to an actual navy storyline that could be implemented into the main game.
